gVehicleClasses = {
        [0] =  "Unbekannt", 			["Unbekannt"] = 0,
        [1] =  "Motorrad",  			["Motorrad"] = 1,
        [2] =  "Roller", 				["Roller"] = 2,
        [3] =  "Crossbike", 			["Crossbike"] = 3,
        [4] =  "Quadbike",  			["Quadbike"] = 4,
        [5] =  "Fahrrad",   			["Fahrrad"] = 5,
        [6] =  "Cabrio",    			["Cabrio"] = 6,
        [7] =  "Low Rider",				["Low Rider"] = 7,
        [8] =  "Gelaendewagen",			["Gelaendewagen"] = 8,
        [9] =  "Limousine",   			["Limousine"] = 9,
        [10] = "Elektroauto",			["Elektroauto"] = 10,
        [11] = "Sportwagen", 			["Sportwagen"] = 11,
        [12] = "Kleinwagen", 			["Kleinwagen"] = 12,
        [13] = "Kombiwagen",  			["Kombiwagen"] = 13,
        [14] = "Industriefahrzeug",     ["Industriefahrzeug"] = 14,
        [15] = "Transportunternehmen",  ["Transportunternehmen"] = 15,
        [16] = "Polizei", 				["Polizei"] = 16,
        [17] = "Feuerwehr", 			["Feuerwehr"] = 17,
        [18] = "Spezialeinheit", 		["Spezialeinheit"] = 18,
        [19] = "Sanitaeter", 			["Sanitaeter"] = 19,
        [20] = "Militaer",   			["Militaer"] = 20,
        [21] = "Spezial",    			["Spezial"] = 21,
        [22] = "Zug", 					["Zug"] = 22,
        [23] = "Flugzeug",   			["Flugzeug"] = 23,
        [24] = "Kampfflugzeug",			["Kampfflugzeug"] = 24,
        [25] = "Hubschrauber", 			["Hubschrauber"] = 25,
        [26] = "Kampfhubschrauber", 	["Kampfhubschrauber"] = 26,
        [27] = "Boot", 					["Boot"] = 27
}
 
 
gVehicleData = {
        [400] = { name = "Landstalker",        class =  8, price =     10935, isPermitted =  true, doors =  5, seats =  4 },
        [401] = { name = "Bravura",            class =  9, price =      8435, isPermitted =  true, doors =  3, seats =  2 },
        [402] = { name = "Buffalo",            class = 11, price =     41229, isPermitted =  true, doors =  3, seats =  2 },
        [403] = { name = "Linerunner",         class =  8, price =    102609, isPermitted =  true, doors =  2, seats =  2 },
		[404] = { name = "Perennial",          class = 13, price =      6277, isPermitted =  true, doors =  5, seats =  4 },
        [405] = { name = "Sentinel",           class =  9, price =      9720, isPermitted =  true, doors =  5, seats =  4 },
        [406] = { name = "Dumper",             class = 21, price =    179712, isPermitted =  true, doors =  1, seats =  1 },
        [407] = { name = "Firetruck",          class = 17, price =    364500, isPermitted =  true, doors =  3, seats =  2 },
        [408] = { name = "Trashmaster",        class = 14, price =    142398, isPermitted =  true, doors =  2, seats =  2 },
        [409] = { name = "Stretch",            class = 21, price =     55890, isPermitted =  true, doors =  5, seats =  4 },
        [410] = { name = "Manana",             class =  9, price =      5665, isPermitted =  true, doors =  3, seats =  2 },
        [411] = { name = "Infernus",           class = 11, price =    141750, isPermitted =  true, doors =  3, seats =  2 },
        [412] = { name = "Voodoo",             class =  7, price =     14377, isPermitted =  true, doors =  3, seats =  2 },
        [413] = { name = "Pony",               class = 14, price =      8999, isPermitted =  true, doors =  5, seats =  4 },
        [414] = { name = "Mule",               class =  8, price =     44200, isPermitted =  true, doors =  3, seats =  2 },
		[415] = { name = "Cheetah",            class = 11, price =     95579, isPermitted =  true, doors =  3, seats =  2 },
        [416] = { name = "Ambulance",          class = 19, price =     88487, isPermitted =  true, doors =  5, seats =  4 },
        [417] = { name = "Leviathan",          class = 25, price =    291195, isPermitted =  true, doors =  2, seats =  2 },
        [418] = { name = "Moonbeam",           class = 13, price =      3199, isPermitted =  true, doors =  5, seats =  4 },
        [419] = { name = "Esperanto",          class =  9, price =     11947, isPermitted =  true, doors =  3, seats =  2 },
        [420] = { name = "Taxi",               class = 15, price =     13769, isPermitted =  true, doors =  5, seats =  4 },
        [421] = { name = "Washington",         class =  9, price =     15349, isPermitted =  true, doors =  5, seats =  4 },
        [422] = { name = "Bobcat",             class =  8, price =      3037, isPermitted =  true, doors =  3, seats =  2 },
		[423] = { name = "Mr Whoopee",         class = 21, price =     23490, isPermitted =  true, doors =  3, seats =  2 },
        [424] = { name = "BF Injection",       class =  8, price =      8901, isPermitted =  true, doors =  0, seats =  2 },
        [425] = { name = "Hunter",             class = 26, price =    64800000, isPermitted =  true, doors =  1, seats =  1 },
        [426] = { name = "Premier",            class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [427] = { name = "Enforcer",           class = 16, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [428] = { name = "Securitycar",        class = 21, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [429] = { name = "Banshee",            class = 11, price =    103497, isPermitted =  true, doors =  3, seats =  2 },
        [430] = { name = "Predator",           class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [431] = { name = "Bus",                class = 15, price =    0, isPermitted =  true, doors =  2, seats = -1 },
        [432] = { name = "Rhino",              class = 20, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [433] = { name = "Barracks",           class = 20, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [434] = { name = "Hotknife",           class = 21, price =    0, isPermitted =  true, doors =  3, seats =  2 },
      	[436] = { name = "Previon",            class =  9, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [437] = { name = "Coach",              class = 15, price =    0, isPermitted =  true, doors =  2, seats = -1 },
        [438] = { name = "Cabbie",             class = 15, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [439] = { name = "Stallion",           class =  6, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [440] = { name = "Rumpo",              class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
	 	[442] = { name = "Romero",             class = 21, price =    45283, isPermitted =  true, doors =  3, seats =  2 },
        [443] = { name = "Packer",             class = 12, price =    185980, isPermitted =  true, doors =  3, seats =  2 },
		[444] = { name = "Monster",            class =  8, price =    190621, isPermitted =  true, doors =  3, seats =  2 },
        [445] = { name = "Admiral",            class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [446] = { name = "Squallo",            class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [447] = { name = "Seasparrow",         class = 26, price =    0, isPermitted =  true, doors =  2, seats =  2 },
        [448] = { name = "Pizzaboy",           class =  2, price =    6074, isPermitted =  true, doors =  0, seats =  1 },
    	[451] = { name = "Turismo",            class = 11, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [452] = { name = "Speeder",            class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [453] = { name = "Reefer",             class = 27, price =    00, isPermitted =  true, doors =  0, seats =  1 },
        [454] = { name = "Tropic",             class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [455] = { name = "Flatbed",            class =  8, price =    100359, isPermitted =  true, doors =  3, seats =  2 },
		[456] = { name = "Yankee",             class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
		[457] = { name = "Caddy",              class = 21, price =    2511, isPermitted =  true, doors =  0, seats =  2 },
        [458] = { name = "Solair",             class = 13, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [460] = { name = "Skimmer",            class = 23, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [461] = { name = "PCJ-600",            class =  1, price =    0, isPermitted =  true, doors =  0, seats =  2 },
        [462] = { name = "Faggio",             class =  2, price =    0, isPermitted =  true, doors =  0, seats =  2 },
        [463] = { name = "Freeway",            class =  1, price =    6074, isPermitted =  true, doors =  0, seats =  2 },
     	[466] = { name = "Glendale",           class =  9, price =    25839, isPermitted =  true, doors =  5, seats =  4 },
        [467] = { name = "Oceanic",            class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [468] = { name = "Sanchez",            class =  3, price =    0, isPermitted =  true, doors =  0, seats =  2 },
        [469] = { name = "Sparrow",            class = 25, price =    0, isPermitted =  true, doors =  2, seats =  2 },
        [470] = { name = "Patriot",            class =  8, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [471] = { name = "Quad",               class =  4, price =    0, isPermitted =  true, doors =  0, seats =  2 },
        [472] = { name = "Kuestenwache",       class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [473] = { name = "Dinghy",             class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [472] = { name = "Coastguard",         class = 27, price =    0, isPermitted =  true, doors =  0, seats =  2 },
        [474] = { name = "Hermes",             class =  9, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [475] = { name = "Sabre",              class = 11, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [476] = { name = "Rustler",            class = 24, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [477] = { name = "ZR-350",             class = 11, price =    60660, isPermitted =  true, doors =  3, seats =  2 },
        [478] = { name = "Walton",             class = 14, price =    0, isPermitted =  true, doors =  2, seats =  2 },
        [479] = { name = "Regina",             class = 13, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [480] = { name = "Comet",              class =  6, price =    43667, isPermitted =  true, doors =  3, seats =  2 },
        [481] = { name = "BMX",                class =  5, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [482] = { name = "Burrito",            class = 14, price =    15795, isPermitted =  true, doors =  4, seats =  4 },
        [483] = { name = "Camper",             class = 21, price =    144585, isPermitted =  true, doors =  4, seats =  2 },
        [484] = { name = "Marquis",            class = 27, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [485] = { name = "Baggage",            class = 21, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [486] = { name = "Dozer",              class = 21, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [487] = { name = "Maverick",           class = 25, price =    0, isPermitted =  true, doors =  4, seats =  4 },
        [488] = { name = "NewsMaverick",       class = 25, price =    0, isPermitted =  true, doors =  3, seats =  2 },
		[489] = { name = "Rancher",            class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [490] = { name = "FBI-Rancher",        class = 18, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [491] = { name = "Virgo",              class =  9, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [492] = { name = "Greenwood",          class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [493] = { name = "Jetmax",             class = 27, price =    94553, isPermitted =  true, doors =  0, seats =  1 },
        [495] = { name = "Sandking",           class =  8, price =    121500, isPermitted =  true, doors =  3, seats =  2 },
        [496] = { name = "Blista-Compact",     class = 12, price =    7199, isPermitted =  true, doors =  3, seats =  2 },
        [497] = { name = "Maverick",           class = 25, price =    0, isPermitted =  true, doors =  4, seats =  4 },
        [498] = { name = "Boxvill",            class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
		[499] = { name = "Benson",             class =  8, price =    0, isPermitted =  true, doors =  2, seats =  2 },
		[500] = { name = "Mesa",               class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
    	[504] = { name = "Bloodring Banger",   class =  9, price =    0, isPermitted =  true, doors =  0, seats =  2 },
        [505] = { name = "Rancher",            class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [506] = { name = "Super-GT",           class = 11, price =    50211, isPermitted =  true, doors =  3, seats =  2 },
        [507] = { name = "Elegant",            class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [508] = { name = "Journey",            class = 21, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [509] = { name = "Bike",               class =  5, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [510] = { name = "Mountain Bike",      class =  5, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [511] = { name = "Beagle",             class = 23, price =    0, isPermitted =  true, doors =  2, seats =  2 },
        [512] = { name = "Cropduster",         class = 24, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [513] = { name = "Stuntplane",         class = 23, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [514] = { name = "Tanklaster",         class =  8, price =    0, isPermitted =  true, doors =  3, seats =  2 },
		[515] = { name = "Roadtrain",          class = 14, price =    96504, isPermitted =  true, doors =  2, seats =  2 },
        [516] = { name = "Nebula",             class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [517] = { name = "Majestic",           class =  9, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [518] = { name = "Buccaneer",          class =  9, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [519] = { name = "Shamal",             class = 23, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [520] = { name = "Hydra",              class = 24, price =    11826000, isPermitted =  true, doors =  1, seats =  1 },
        [521] = { name = "FCR-900",            class =  1, price =    42921, isPermitted =  true, doors =  0, seats =  2 },
        [522] = { name = "NRG-500",            class =  1, price =    81000, isPermitted =  true, doors =  0, seats =  2 },
        [523] = { name = "HPV1000",            class = 16, price =    18225, isPermitted =  true, doors =  0, seats =  2 },
        [524] = { name = "Cement Truck",       class =  8, price =    131949, isPermitted =  true, doors =  3, seats =  2 },
		[525] = { name = "Abschlepper",        class = 21, price =    61596, isPermitted =  true, doors =  2, seats =  2 },
        [526] = { name = "Fortune",            class =  9, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [527] = { name = "Cadrona",            class = 10, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [528] = { name = "FBI-Truck",          class = 18, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [529] = { name = "Willard",            class =  9, price =    0, isPermitted =  true, doors =  5, seats =  4 },
        [530] = { name = "Forklift",           class = 21, price =    0, isPermitted =  true, doors =  0, seats =  1 },
        [531] = { name = "Tractor",            class = 27, price =    0, isPermitted =  true, doors =  0, seats =  2 },
		[532] = { name = "Maehdrescher",       class = 21, price =    0, isPermitted =  true, doors =  1, seats =  1 },
        [533] = { name = "Feltzer",            class =  6, price =    0, isPermitted =  true, doors =  3, seats =  2 },
        [534] = { name = "Remington",          class =  7, price =    56659, isPermitted =  true, doors =  3, seats =  2 },
        [535] = { name = "Slamvan",            class =  7, price =    38799, isPermitted =  true, doors =  3, seats =  2 },
        [536] = { name = "Blade",              class =  7, price =    31549, isPermitted =  true, doors =  3, seats =  2 },
        [540] = { name = "Vincent",            class =  9, price =    8100, isPermitted =  true, doors =  5, seats =  4 },
        [541] = { name = "Bullet",             class = 11, price =    63909, isPermitted =  true, doors =  3, seats =  2 },
        [542] = { name = "Clover",             class =  9, price =    6075, isPermitted =  true, doors =  3, seats =  2 },
        [543] = { name = "Sadler",             class =  8, price =    19439, isPermitted =  true, doors =  3, seats =  2 },
		[544] = { name = "FiretruckL",		   class = 17, price =    138737, isPermitted =  true, doors =  3, seats =  2 },
        [545] = { name = "Hustler",            class = 21, price =    15187, isPermitted =  true, doors =  3, seats =  2 },
        [546] = { name = "Intruder",           class =  9, price =    10935, isPermitted =  true, doors =  5, seats =  4 },
        [547] = { name = "Primo",              class = 10, price =    14166, isPermitted =  true, doors =  5, seats =  4 },
        [548] = { name = "Cargobob",           class = 25, price =    20250000, isPermitted =  true, doors =  2, seats =  2 },
        [549] = { name = "Tampa",              class =  9, price =    6439, isPermitted =  true, doors =  3, seats =  2 },
        [550] = { name = "Sunrise",            class =  9, price =    12879, isPermitted =  true, doors =  5, seats =  4 },
        [551] = { name = "Merit",              class =  9, price =    5248, isPermitted =  true, doors =  5, seats =  4 },
        [552] = { name = "Utility-Van",        class = 14, price =    35226, isPermitted =  true, doors =  2, seats =  2 },
        [553] = { name = "Nevada",             class = 23, price =    3196640, isPermitted =  true, doors =  1, seats =  1 },
        [554] = { name = "Yosemite",           class = 14, price =    21060, isPermitted =  true, doors =  3, seats =  2 },
        [555] = { name = "Windsor",            class =  6, price =    105219, isPermitted =  true, doors =  3, seats =  2 },
        [556] = { name = "Monster A",          class = 21, price =    174243, isPermitted =  true, doors =  2, seats =  2 },
        [557] = { name = "Monster B",          class = 21, price =    174243, isPermitted =  true, doors =  2, seats =  2 },
        [558] = { name = "Uranus",             class = 11, price =    18225, isPermitted =  true, doors =  3, seats =  2 },
        [559] = { name = "Jester",             class = 11, price =    36441, isPermitted =  true, doors =  3, seats =  2 },
        [560] = { name = "Sultan",             class =  9, price =    35559, isPermitted =  true, doors =  5, seats =  4 },
        [561] = { name = "Stratum",            class = 13, price =    48519, isPermitted =  true, doors =  5, seats =  4 },
        [562] = { name = "Elegy",              class =  9, price =    40500, isPermitted =  true, doors =  3, seats =  2 },
    	[563] = { name = "Raindance",          class = 25, price =    217890, isPermitted =  true, doors =  2, seats =  2 },
        [565] = { name = "Flash",              class = 12, price =    9720, isPermitted =  true, doors =  3, seats =  2 },
        [566] = { name = "Tahoma",             class =  7, price =    24219, isPermitted =  true, doors =  5, seats =  4 },
        [567] = { name = "Savanna",            class =  7, price =    24138, isPermitted =  true, doors =  5, seats =  4 },
        [568] = { name = "Bandito",            class =  8, price =    15048, isPermitted =  true, doors =  0, seats =  1 },
        [571] = { name = "Kart",               class = 21, price =    4050, isPermitted =  true, doors =  0, seats =  1 },
        [572] = { name = "Mower",              class = 21, price =    2835, isPermitted =  true, doors =  0, seats =  1 },
        [573] = { name = "Dune",               class =  8, price =    139578, isPermitted =  true, doors =  3, seats =  2 },
        [574] = { name = "Sweeper",            class = 21, price =    7290, isPermitted =  true, doors =  1, seats =  1 },
        [575] = { name = "Broadway",           class =  7, price =    32359, isPermitted =  true, doors =  3, seats =  2 },
        [576] = { name = "Tornado",            class =  7, price =    72859, isPermitted =  true, doors =  3, seats =  2 },
        [577] = { name = "AT-400",             class = 23, price =    5467500, isPermitted =  true, doors =  1, seats =  2 },
        [578] = { name = "DFT-30",             class = 14, price =    123401, isPermitted =  true, doors =  3, seats =  2 },
        [579] = { name = "Huntley",            class =  8, price =    9396, isPermitted =  true, doors =  5, seats =  4 },
        [580] = { name = "Stafford",           class =  9, price =    69225, isPermitted =  true, doors =  5, seats =  4 },
        [581] = { name = "BF-400",             class =  1, price =    12060, isPermitted =  true, doors =  0, seats =  2 },
        [582] = { name = "Newsvan",            class = 14, price =    80392, isPermitted =  true, doors =  4, seats =  4 },
        [583] = { name = "Tug",                class = 21, price =    7281, isPermitted =  true, doors =  1, seats =  1 },
    	[585] = { name = "Emperor",            class =  9, price =    13648, isPermitted =  true, doors =  5, seats =  4 },
        [586] = { name = "Wayfarer",           class =  1, price =    12879, isPermitted =  true, doors =  0, seats =  2 },
        [587] = { name = "Euros",              class = 11, price =    17010, isPermitted =  true, doors =  3, seats =  2 },
        [588] = { name = "Hot-Dog",            class = 21, price =    71992, isPermitted =  true, doors =  3, seats =  2 },
        [589] = { name = "Club",               class = 12, price =    11947, isPermitted =  true, doors =  3, seats =  2 },
    	[592] = { name = "Andromada",          class = 23, price =    209369951, isPermitted =  true, doors =  1, seats =  2 },
		[593] = { name = "Dodo",               class = 23, price =    20250, isPermitted =  true, doors =  1, seats =  1 },
    	[595] = { name = "Launch",             class = 27, price =    93150, isPermitted =  true, doors =  0, seats =  1 },
        [596] = { name = "LSPD",               class = 19, price =    81000, isPermitted =  true, doors =  5, seats =  4 },
        [597] = { name = "SFPD",               class = 16, price =    81000, isPermitted =  true, doors =  5, seats =  4 },
        [598] = { name = "LVPD",               class = 16, price =    81000, isPermitted =  true, doors =  5, seats =  4 },
        [599] = { name = "Ranger",             class = 16, price =    81000, isPermitted =  true, doors =  3, seats =  2 },
        [600] = { name = "Picador",            class = 14, price =    9558, isPermitted =  true, doors =  2, seats =  2 },
        [601] = { name = "SWAT",               class = 18, price =    202500, isPermitted =  true, doors =  2, seats =  2 },
        [602] = { name = "Alpha",              class = 11, price =    31585, isPermitted =  true, doors =  3, seats =  2 },
		[603] = { name = "Phoenix",            class = 11, price =    35461, isPermitted =  true, doors =  3, seats =  2 },
		[604] = { name = "Glendale Shit",      class = 11, price =    12919, isPermitted =  true, doors =  5, seats =  4 },
		[605] = { name = "Sadler Shit",        class = 11, price =    9719, isPermitted =  true, doors =  3, seats =  2 },
	}